---
fixtures:
  forge_modules:
    keepalived:
      repo: "puppet/keepalived"
      ref: "2.2.0"
    firewall:
      repo: 'puppetlabs/firewall'
      ref: '2.2.0'
    mysql:
      repo: 'puppetlabs/mysql'
      ref: '10.2.1'
    rpmkey:
      repo: 'stschulte/rpmkey'
      ref: '1.0.3'
    xinetd:
      repo: 'puppetlabs/xinetd'
      ref: '3.3.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '6.0.0'
      # flags: "--module_repository https://my_repo.com"
    yumrepo_core:
      repo: 'puppetlabs/yumrepo_core'
      ref: '1.0.6'

